- clean: ['~', '~/.config']

- shell:
    - mkdir -p ~/.config
    - git submodule update --init --recursive

- link:
    ~/.aliases: .aliases
    ~/bin: bin/
    ~/.compton.conf: .compton.conf
    ~/.config/dunst: .config/dunst
    ~/.dwm: .dwm/
    ~/.fbtermrc: .fbtermrc
    ~/.fonts: .fonts/
    ~/.gitconfig: .gitconfig
    ~/.icons: .icons
    ~/.pentadactyl: .pentadactyl/
    ~/.pentadactylrc: .pentadactylrc
    ~/.st: .st/
    ~/.themes: .themes/
    ~/.tmux: .tmux/
    ~/.tmux.conf: .tmux.conf
    ~/.vimrc: .vim/vimrc
    ~/.vim: .vim/
    ~/.Xresources: .Xresources
    ~/.Xresources.d: .Xresources.d
    ~/.zsh: .zsh/

- shell:
    - for i in zlogin zlogout zpreztorc zprofile zshenv zshrc; do ln -f .zsh/prezto/runcoms/$i ~/.$i; done
