- clean: ['~', '~/.config']

- shell:
    - mkdir -p ~/.config
    - mkdir -p ~/.ncmpcpp
    - mkdir -p ~/.tmux/plugins
    - mkdir -p ~/.mpd/lyrics
    - git submodule update --init --recursive

- link:
    ~/.aliases:        .aliases
    ~/bin:             bin/
    ~/.compton.conf:   .compton.conf
    ~/.config/dunst:   .config/dunst
    ~/.config/termite: .config/termite
    ~/.dircolors:      .dircolors
    ~/.dwm:            .dwm/
    ~/.fbtermrc:       .fbtermrc
    ~/.fonts:          .fonts/
    ~/.gitconfig:      .gitconfig
    ~/.icons:          .icons
    ~/.mpdconf:        .mpdconf
    ~/.ncmpcpp/config: .ncmpcpp/config
    ~/.pentadactyl:    .pentadactyl/
    ~/.pentadactylrc:  .pentadactylrc
    ~/.st:             .st/
    ~/.themes:         .themes/
    ~/.tmux.conf:      .tmux.conf
    ~/.Xresources:     .Xresources
    ~/.Xresources.d:   .Xresources.d
    ~/.zlogin:         .zsh/prezto/runcoms/zlogin
    ~/.zlogout:        .zsh/prezto/runcoms/zlogout
    ~/.zpreztorc:      .zsh/prezto/runcoms/zpreztorc
    ~/.zprofile:       .zsh/prezto/runcoms/zprofile
    ~/.zshenv:         .zsh/prezto/runcoms/zshenv
    ~/.zshrc:          .zsh/prezto/runcoms/zshrc
    ~/.zsh:            .zsh/

- shell:
    - mv $HOME/.emacs.d $HOME/.emacs.d.old
    - git clone https://github.com/blissner/doom-emacs/ $HOME/.emacs.d -b develop
    - git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm

