- clean: ['~', '~/.config']

- shell:
    - mkdir -p ~/.config
    - git submodule update --init --recursive

- link:
    ~/.aliases: aliases
    ~/.compton.conf: compton.conf
    ~/.fbtermrc: fbtermrc
    ~/.Xresources: Xresources
    ~/.gitconfig: gitconfig
    ~/.tmux.conf: tmux.conf
    ~/.vim: vim/
    ~/.vimrc: vim/vimrc
    ~/.zsh: zsh/

- shell:
